//! Device identity — the master secret, TG-scoped key derivation, and the
//! storage **seam** (R2-HIVE north-star: portable identity in hive-core; only
//! the backing store is platform code).
//!
//! Implements the model from R2-WIRE §6.2.1 and R2-TRUST §2.3: a single
//! `device_master_secret` lives on the device; everything observable on the
//! wire (`hive_id`, `DEV_PK`, `DEV_SK`) is deterministically derived from it
//! plus the current `trust_group_id`. Rejoining the same TG reproduces the
//! same derived identities. Across TGs, identities are unlinkable.
//!
//! This module is `no_std` + `alloc`: the crypto (HKDF-SHA256 derivation,
//! Ed25519 keypair, fingerprint, UUID formatting) has no platform dependency,
//! so the same identity runs on Linux/cloud, ESP32-S3, and the wasm hive. The
//! concrete [`IdentityStore`] backends (file, keyring, flash, IndexedDB) live
//! in each platform layer; this module only defines the trait + its
//! platform-neutral error/backend types.

use alloc::format;
use alloc::string::String;

use ed25519_dalek::{SigningKey, VerifyingKey};
use hkdf::Hkdf;
use sha2::{Digest, Sha256};
use zeroize::ZeroizeOnDrop;

/// Length of the device master secret in bytes (256 bits).
pub const MASTER_SECRET_LEN: usize = 32;

/// Per-TG derived identities.
pub struct DerivedIdentity {
    /// UUID-formatted hive ID (RFC 4122 §4.4). Deterministic per (master, tg).
    pub hive_id: String,
    pub verifying_key: VerifyingKey,
    signing_key: SigningKey,
}

impl DerivedIdentity {
    /// Access the Ed25519 signing key. Callers hold this only for the lifetime
    /// of an active hive's needs; keys are zeroized when the `DerivedIdentity`
    /// drops.
    pub fn signing_key(&self) -> &SigningKey {
        &self.signing_key
    }
}

impl Drop for DerivedIdentity {
    fn drop(&mut self) {
        // SigningKey in ed25519-dalek 2.x does not auto-zeroize; we don't have
        // mutable access to its internal bytes via public API, but dropping the
        // struct at least drops the allocation. A stronger zeroization would
        // require a wrapper; tracked for Phase 1+.
        //
        // The hive_id is public; no need to scrub.
        let _ = &self.signing_key;
    }
}

/// The daemon's custody of the device master secret.
///
/// `MasterSecret` holds the raw bytes in process memory. It is `ZeroizeOnDrop`
/// so tearing down the holder scrubs the memory. The bytes MUST NOT be copied
/// out via any wire/API surface — only the derivation helpers on this type and
/// [`MasterSecret::expose_secret_bytes`] (storage backends only) may observe
/// them.
#[derive(ZeroizeOnDrop)]
pub struct MasterSecret {
    bytes: [u8; MASTER_SECRET_LEN],
}

impl MasterSecret {
    /// Construct from raw bytes (e.g. freshly generated by a platform CSPRNG,
    /// or loaded from a store). Identity generation itself is a platform
    /// concern (the RNG lives in the platform layer); the core only takes the
    /// resulting bytes.
    pub fn from_bytes(bytes: [u8; MASTER_SECRET_LEN]) -> Self {
        Self { bytes }
    }

    /// Raw secret bytes — **storage backends only**, for persisting the secret
    /// to a backing store. MUST NOT be surfaced on any wire/API/log surface.
    /// (Crypto consumers use [`derive`](Self::derive) /
    /// [`derive_web_auth_key`](Self::derive_web_auth_key) instead.)
    pub fn expose_secret_bytes(&self) -> &[u8; MASTER_SECRET_LEN] {
        &self.bytes
    }

    /// Return a short, stable public identifier suitable for showing to users
    /// in a UI: the first 8 bytes of SHA-256(master_secret), encoded as hex.
    /// This reveals nothing about the master secret by preimage, and lets users
    /// compare devices without exposing keys.
    pub fn fingerprint(&self) -> String {
        let digest = Sha256::digest(self.bytes);
        hex_u8s(&digest[..8])
    }

    /// Derive the per-TG `hive_id` (UUID string) per R2-WIRE §6.2.1.
    fn derive_hive_id(&self, trust_group_id: &str) -> String {
        let mut out = [0u8; 16];
        hkdf_expand(&self.bytes, b"r2-hive-id-v1", trust_group_id.as_bytes(), &mut out);
        format_uuid(&out)
    }

    /// Derive the per-TG Ed25519 signing key seed.
    fn derive_dev_sk_seed(&self, trust_group_id: &str) -> [u8; 32] {
        let mut out = [0u8; 32];
        hkdf_expand(&self.bytes, b"r2-dev-key-v1", trust_group_id.as_bytes(), &mut out);
        out
    }

    /// Full per-TG derivation: hive_id + Ed25519 keypair.
    pub fn derive(&self, trust_group_id: &str) -> DerivedIdentity {
        let hive_id = self.derive_hive_id(trust_group_id);
        let seed = self.derive_dev_sk_seed(trust_group_id);
        let signing_key = SigningKey::from_bytes(&seed);
        let verifying_key = signing_key.verifying_key();
        DerivedIdentity {
            hive_id,
            verifying_key,
            signing_key,
        }
    }

    /// Derive a 32-byte HMAC key for web-plugin browser-cookie signing
    /// (R2-PLUGIN §13.5). Distinct HKDF info string from the per-TG
    /// device key so cookie compromise can't impersonate the TG-bound
    /// keypair.
    pub fn derive_web_auth_key(&self) -> [u8; 32] {
        let mut out = [0u8; 32];
        hkdf_expand(&self.bytes, b"r2-web-auth-cookie-v1", b"", &mut out);
        out
    }
}

/// HKDF-SHA256 in the argument order used by R2-WIRE §6.2.1:
/// extract(salt) then expand(info) into the provided output buffer.
fn hkdf_expand(ikm: &[u8], salt: &[u8], info: &[u8], out: &mut [u8]) {
    let h = Hkdf::<Sha256>::new(Some(salt), ikm);
    h.expand(info, out).expect("output length within HKDF limit");
}

fn hex_u8s(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut s = String::with_capacity(bytes.len() * 2);
    for &b in bytes {
        s.push(HEX[(b >> 4) as usize] as char);
        s.push(HEX[(b & 0x0F) as usize] as char);
    }
    s
}

/// Format 16 bytes as a UUID string per RFC 4122 §4.4.
fn format_uuid(b: &[u8; 16]) -> String {
    // Set version (4) and variant (RFC 4122) bits per §4.4 so the result is a
    // well-formed UUIDv4 string.
    let mut v = *b;
    v[6] = (v[6] & 0x0F) | 0x40; // version 4
    v[8] = (v[8] & 0x3F) | 0x80; // variant 10
    format!(
        "{:02x}{:02x}{:02x}{:02x}-{:02x}{:02x}-{:02x}{:02x}-{:02x}{:02x}-{:02x}{:02x}{:02x}{:02x}{:02x}{:02x}",
        v[0], v[1], v[2], v[3], v[4], v[5], v[6], v[7],
        v[8], v[9], v[10], v[11], v[12], v[13], v[14], v[15],
    )
}

// ───────────────────────── Storage seam ─────────────────────────

/// Backends a hive can use to hold the master secret. The set is fixed here so
/// `r2.mgmt.identity.status` reporting is platform-neutral; each platform layer
/// implements whichever variants it supports (Linux ships `File` always and
/// `Libsecret` under a feature; an MCU would add a flash-backed one mapped to
/// its own tag, wasm an IndexedDB-backed one).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StoreBackend {
    File,
    Libsecret,
    Keychain,
    WinCred,
    None,
}

impl StoreBackend {
    pub fn as_str(self) -> &'static str {
        match self {
            StoreBackend::File => "file",
            StoreBackend::Libsecret => "libsecret",
            StoreBackend::Keychain => "keychain",
            StoreBackend::WinCred => "wincred",
            StoreBackend::None => "none",
        }
    }
}

/// Platform-neutral error for [`IdentityStore`] operations. Platform backends
/// map their native errors (e.g. `std::io::Error`, a keyring error, a flash
/// driver error) into these variants; hive-core code handles the trait without
/// depending on any platform error type.
#[derive(Debug)]
pub enum StoreError {
    /// The backing store reported corrupt/wrong-shaped data (e.g. a key blob
    /// of the wrong length).
    InvalidData(String),
    /// Any other backend failure (IO, permissions, keyring/DBus, flash). The
    /// string is a human-readable description for logs/`identity.status`.
    Backend(String),
}

impl core::fmt::Display for StoreError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            StoreError::InvalidData(s) => write!(f, "identity store: invalid data: {s}"),
            StoreError::Backend(s) => write!(f, "identity store: {s}"),
        }
    }
}

/// Common interface implemented by every concrete master-secret store.
///
/// Lifetime: the store value is constructed at startup, used for
/// [`IdentityStore::load_or_create`], and dropped. The loaded [`MasterSecret`]
/// is held by the daemon/firmware state from then on; the store itself doesn't
/// need to stay alive.
pub trait IdentityStore {
    /// Load the master secret from this backend, or create+persist a fresh one
    /// if none is present. Returns `(secret, created)` where `created` is `true`
    /// iff this call generated a new secret.
    fn load_or_create(&self) -> Result<(MasterSecret, bool), StoreError>;

    /// Backend tag for `r2.mgmt.identity.status` reporting.
    fn backend(&self) -> StoreBackend;

    /// Operator-readable identifier for the store (e.g. a filesystem path, or a
    /// DBus path). Surfaced in `r2.mgmt.identity.status`.
    fn display_path(&self) -> String;
}

// ───────────────────────── Tests ─────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::vec::Vec;

    // Fixed master secret for deterministic testing.
    fn fixture_secret() -> MasterSecret {
        let mut bytes = [0u8; MASTER_SECRET_LEN];
        for (i, b) in bytes.iter_mut().enumerate() {
            *b = i as u8;
        }
        MasterSecret::from_bytes(bytes)
    }

    #[test]
    fn fingerprint_is_stable_and_16_hex_chars() {
        let s = fixture_secret();
        let fp1 = s.fingerprint();
        let fp2 = s.fingerprint();
        assert_eq!(fp1, fp2);
        assert_eq!(fp1.len(), 16);
        assert!(fp1.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn derive_same_tg_twice_gives_same_identity() {
        let s = fixture_secret();
        let a = s.derive("tg-alpha");
        let b = s.derive("tg-alpha");
        assert_eq!(a.hive_id, b.hive_id);
        assert_eq!(a.verifying_key.to_bytes(), b.verifying_key.to_bytes());
    }

    #[test]
    fn derive_different_tgs_gives_different_identities() {
        let s = fixture_secret();
        let a = s.derive("tg-alpha");
        let b = s.derive("tg-beta");
        assert_ne!(a.hive_id, b.hive_id);
        assert_ne!(a.verifying_key.to_bytes(), b.verifying_key.to_bytes());
    }

    #[test]
    fn derive_is_different_per_master_secret() {
        let s1 = fixture_secret();
        let mut other = [0u8; MASTER_SECRET_LEN];
        other[0] = 0xFF; // differ from fixture
        let s2 = MasterSecret::from_bytes(other);

        let a = s1.derive("tg-alpha");
        let b = s2.derive("tg-alpha");
        assert_ne!(a.hive_id, b.hive_id);
        assert_ne!(a.verifying_key.to_bytes(), b.verifying_key.to_bytes());
    }

    #[test]
    fn hive_id_is_well_formed_uuid_v4() {
        let s = fixture_secret();
        let id = s.derive("tg-alpha").hive_id.clone();
        // 8-4-4-4-12 hex layout = 36 chars total including dashes.
        assert_eq!(id.len(), 36);
        let parts: Vec<&str> = id.split('-').collect();
        assert_eq!(parts.len(), 5);
        assert_eq!(parts[0].len(), 8);
        assert_eq!(parts[1].len(), 4);
        assert_eq!(parts[2].len(), 4);
        assert_eq!(parts[3].len(), 4);
        assert_eq!(parts[4].len(), 12);
        // UUIDv4 version nibble: first char of group 3 must be '4'.
        assert_eq!(parts[2].chars().next().unwrap(), '4');
        // Variant: first char of group 4 must be 8, 9, a, or b.
        let var = parts[3].chars().next().unwrap();
        assert!(matches!(var, '8' | '9' | 'a' | 'b'));
    }

    #[test]
    fn store_backend_as_str_covers_every_variant() {
        // If a new variant is added, this test forces a deliberate
        // string mapping update.
        for v in [
            StoreBackend::File,
            StoreBackend::Libsecret,
            StoreBackend::Keychain,
            StoreBackend::WinCred,
            StoreBackend::None,
        ] {
            assert!(!v.as_str().is_empty());
        }
    }

    #[test]
    fn expose_secret_bytes_round_trips_through_from_bytes() {
        let s = fixture_secret();
        let bytes = *s.expose_secret_bytes();
        let s2 = MasterSecret::from_bytes(bytes);
        assert_eq!(s.fingerprint(), s2.fingerprint());
    }
}
